### ISSUE TITLE
Allow configuring a custom beat saver endpoint

### ISSUE THREAD

**Issue by peddermaster2** [InnocentThief/Custom-Songs-Manager#10]

**Comment by InnocentThief** [comment]
Comes with the first "Twitch Integration" release
![BeatSaverAPICustomConfig](https://user-images.githubusercontent.com/65510170/174445802-acc8e0ce-d2ff-43df-bb0a-dfcc9b81475d.png)

**Comment by peddermaster2** [comment]
Perfect.
Cuz I have a caching server for `api.beatsaver.com`.

Any ETA?

**Comment by InnocentThief** [comment]
If you're fine with getting an Alpha version I can send you an early release today

**Comment by peddermaster2** [comment]
Yeah.

**Comment by peddermaster2** [comment]
Works great (after a app restart).

**Comment by InnocentThief** [comment]
I'll add an info that restart is required and if changed by accident to just clear the field. It will be set to default if empty

**Comment by InnocentThief** [comment]
Done in 1.4.2.0
