### ISSUE TITLE
The app does not set a user agent reqest header for API requests

### ISSUE THREAD

**Issue by peddermaster2** [InnocentThief/Custom-Songs-Manager#15]
It is encuraged and goot practice to send a `User-Agent` header.  
Some servers (not in this case) reject requests without that header.

I propose something like `Custom-Songs-Manager/1.4.0.0` where the version part is the current app version.

For more information: https://httpwg.org/specs/rfc7231.html#header.user-agent

**Comment by InnocentThief** [comment]
Done in Version 1.4.2.0
