### ISSUE TITLE
Some invalid requests are send to the API

### ISSUE THREAD

**Issue by peddermaster2** [InnocentThief/Custom-Songs-Manager#17]
This request are captured in the API access log.  
The "Twitch" pane is active with >= 1 active stream.

```
127.0.0.1:58711 "GET /maps/id/(bsr HTTP/1.1" 404 "-" "-" 214.5109ms 
127.0.0.1:58711 "GET /maps/id/Turn HTTP/1.1" 404 "-" "-" 225.7637ms  
127.0.0.1:58711 "GET /maps/id/(bsr HTTP/1.1" 404 "-" "-" 205.2603ms    
127.0.0.1:58711 "GET /maps/id/Complex HTTP/1.1" 404 "-" "-" 174.7759ms   
```

It looks like `(bsr` is always followed by the first word of the song title.

Most likely cause are chat messages like  
`CallmeJodie: ! (bsr 195db) Complex [Kiseijuu: Sei no Kakuritsu] / FakePope 76% requested by @dertmol added to queue.`

**Comment by peddermaster2** [comment]
Additional note:  
Is it possible that every message that starts with a `!` is split on the first 2 spaces and then the word inbetween is used?

**Comment by InnocentThief** [comment]
Other messages than !bsr are not implemented yet

- allways exclude "! "  
- get bsr key from !link command

**Comment by peddermaster2** [comment]
I think you got my message wrong.  
The current behavoir is what I described in https://github.com/InnocentThief/Custom-Songs-Manager/issues/17#issuecomment-1159555124

**Comment by InnocentThief** [comment]
Pls check in next version

**Comment by peddermaster2** [comment]
Fixed.
