### ISSUE TITLE
Workspace Playlist autoupdate Songname / SongAuthor / Mapper / DifficultyName on selection

### ISSUE THREAD

**Issue by GoodOldNervy** [InnocentThief/Custom-Songs-Manager#37]
Some Playlists contain but a hash, enlarge Json/Bplist with mentioned Info when details of a Song are shown (already done with Column BSR)

![image](https://user-images.githubusercontent.com/61086688/197395958-0ec80cbb-5790-4374-8e09-189480bbf72b.png)

**Comment by InnocentThief** [comment]
Done in version 1.5.0.0
