### ISSUE TITLE
Workspace CustomLevels allow a generate of a (Save-)Playlist 

### ISSUE THREAD

**Issue by GoodOldNervy** [InnocentThief/Custom-Songs-Manager#39]
Simple Playlist just containing basic Information (e.g. hash) of all downloaded CustomLevels to rebuild custom levels if necessary, named something like yy-mm-dd-SavedCustemLevelsReferences in Playlists

Optional goodie: let the user define Path of this Playlist in Settings

**Comment by InnocentThief** [comment]
Done in version 1.5.0.0
