### ISSUE TITLE
Absturz beim Hinzufügen einer nicht mehr verfügbaren Map zu einer Playlist

### ISSUE THREAD

**Issue by Tindux** [InnocentThief/Custom-Songs-Manager#46]
Die untere Map wurde auf Beatsaver geupdatet. 

![image](https://github.com/InnocentThief/Custom-Songs-Manager/assets/146855257/efcee73c-662b-4c65-b6a5-e543e3a91639)
 
Ursprünglicher bsr ist 339d3
 
![image](https://github.com/InnocentThief/Custom-Songs-Manager/assets/146855257/43ee0907-9e51-421d-b1a8-c23c739c32e6)

Beim Hinzufügen dieser Map zu einer Playlist schließt sich das Programm.
![image](https://github.com/InnocentThief/Custom-Songs-Manager/assets/146855257/e4d49802-03eb-48ba-9cba-0173f7596b06)

Hier wäre eine Meldung schön, dass es nicht geht, weil es diese Map nicht mehr gibt.
Danke (ich hoffe, die Bilder werden angezeigt)

**Comment by InnocentThief** [comment]
Hallo
Kannst Du mir bitte das Verzeichnis inklusive den Dateien zukommen lassen? Werde dann eine entsprechende Anpassung vornehmen.
Danke

**Comment by Tindux** [comment]
Hi Inno,

 

erst mal viiiielen Dank für die viele Arbeit so eine Datenbank aufzubauen.

Ich würde dir gerne zuschicken, was du brauchst, habe allerdings keine Ahnung wovon du sprichst, bin ein einfacher user.

 

Oder meinst du, ich soll dir den Ordner schicken "Custom Songs Manager" ?

Sorry und liebe Grüße

 

 
 

Gesendet: Dienstag, 07. November 2023 um 08:15 Uhr
Von: "InnocentThief" ***@***.***>
An: "InnocentThief/Custom-Songs-Manager" ***@***.***>
Cc: "Tindux" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [InnocentThief/Custom-Songs-Manager] Absturz beim Hinzufügen einer nicht mehr verfügbaren Map zu einer Playlist (Issue #46)


 

Hallo
Kannst Du mir bitte das Verzeichnis inklusive den Dateien zukommen lassen? Werde dann eine entsprechende Anpassung vornehmen.
Danke

**Comment by InnocentThief** [comment]
Salü 
Kein Problem. Es geht um die beiden Songverzeichnisse 
- 33cd8-Jonas Blue, Felix Jeahn - Weekends
- 339d3 ( Weekends - mag1)

Wenn Du die beiden Zippen kannst und hier anhängst (Button mit dem Bild einer Klammer) , kann ich die Anpassung vornehmen.

**Comment by Tindux** [comment]
Bitteschön und vielen Dank
[33cd8-Jonas Blue, Felix Jaehn -  Weekends.zip](https://github.com/InnocentThief/Custom-Songs-Manager/files/13326118/33cd8-Jonas.Blue.Felix.Jaehn.-.Weekends.zip)
[339d3 ( Weekends - mag1).zip](https://github.com/InnocentThief/Custom-Songs-Manager/files/13326119/339d3.Weekends.-.mag1.zip)
